/*
 This file created by convert_cpp_cmd2defines with the following command
 line arguments:
 Warning - this file is automatically generated - do NOT edit -UALLOW_ADJOINT_RUN -UALLOW_TANGENTLINEAR_RUN -UALLOW_ECCO_OPTIMIZATION
*/

/*  Warning - this file is automatically generated - do NOT edit  */
#undef  ALLOW_ADJOINT_RUN
#undef  ALLOW_TANGENTLINEAR_RUN
#undef  ALLOW_ECCO_OPTIMIZATION
